export enum APPLICATION {
    PRODUCT_TITLE_RELATED_PRODUCTS = "Related Products",
    PRODUCT_TITLE_PRODUCTS = "Products",
    PRODUCT_TITLE_PRODUCTS_FILTER = "Products Filter",
    PRODUCT_MAX_PRICE = "10000000"
}